### ISSUE TITLE
Playtest notes

### ISSUE THREAD

**Issue by xen-42** [xen-42/ow-mod-jam-4#2]
- For those hard of hearing: Add some colour indicators to the signal puzzle? Maybe button colour changes and can match something on the jammer.
- Maybe we should indicate where you can stand to have it line up with the jammer because it makes it much easier to test guesses.
- Rename "key 1" to glowing hexagon
- Change glowing item colours to not prevent seeing
- Ixrec looked directly at the white arrow and didn't get it. Maybe if it was a different colour? Or if the shape actually matched the shapes on the box? Otherwise I think the hidden arrows might be too hidden. Could put one behind the box since people look there more.
- Remove black arrow colour bc confusing.
- If you press too many chess buttons, turn them all off
- Infinity guy has bad bounding box
- When you take a photo of the quantum guys we should have a diagram in back directing you to check the hanger for the sequence (this would also highlight secret codes revealed by photos, since Ixrec missed the code on the ceiling). Alternatively, play some pillar music.
- Mobius can appear twice -> Pyramid was vanished from existence. Will come back though.  Not ideal!
- Third scroll might be too hidden, could bring it forward or have it stick out further
- Make coordinates glow like ghost matter
- Maybe in Nomai interface puzzle ship log we emphasize how it moves up and down? Emphasize that the gravity field is stuck on (maybe a broken interface to turn it off). Maybe only have the gravity field at the very top of the corner so it doesn't affect you getting onto the platform. Could also make the platform wider at the top so that standing on it feels purposeful.
- Changing the totems to just be a toggle and not actually use the flashlight OR add a stranger artifact. Too easy to accidentally turn on the totems
- Could remove extinguish prompts from candles since its not relevant
- Add Ernesto
- Maybe add lights to the totems
- Lining up totems maybe too precise?
- Make the three coloured arrows stop being interactive after both puzzles are solved
- Could get a more obvious hint that you want to go to the map mode, since they never open map mode they dont know about the double-hexagon until they read the hint
- Ixrec thought the upsidedown coords + leftshift meant to rightshift them rightside up, but figured out the right solution after that didnt work
- He wrote down all the map mode symbols, took a while to realize up meant go up. Could have the symbols be > > > > > ^ < <
- Mute ambient music when using signalscope in the hanger
- Make nomai scrolls more obviously point in a direction. Maybe the text could have an arrow?

**Comment by GameWyrm** [comment]
> For those hard of hearing: Add some colour indicators to the signal puzzle? Maybe button colour changes and can match something on the jammer.

If we do something to make the jammer puzzle easier, it should probably be a config option tbh. Ixrec has hearing problems but was able to solve it easily since the wrong instruments are very clearly incorrect.

> Maybe we should indicate where you can stand to have it line up with the jammer because it makes it much easier to test guesses.

I feel it's really easy to do that on your own, we don't want to be *too* hand-holdy.

> Rename "key 1" to glowing hexagon

Easy. Should also add these to translation file.

> Change glowing item colours to not prevent seeing

I like how they look, I wonder if we could change the prompt color instead to be a light grey?

> Ixrec looked directly at the white arrow and didn't get it. Maybe if it was a different colour? Or if the shape actually matched the shapes on the box? Otherwise I think the hidden arrows might be too hidden. Could put one behind the box since people look there more.

He realized what it meant once he found another arrow. I think the bigger issue based on a couple other playtests is that people don't realize they need to investigate everything from every angle, which is generally expected from Escape Rooms. I'll add a hint to one of the ship logs suggesting you should look around more.

> Remove black arrow colour bc confusing.

Sure.

> If you press too many chess buttons, turn them all off

Yeah. Probably five, so four are lit and the fifth one turns them all off.

> Infinity guy has bad bounding box

Weird.

> When you take a photo of the quantum guys we should have a diagram in back directing you to check the hanger for the sequence (this would also highlight secret codes revealed by photos, since Ixrec missed the code on the ceiling). Alternatively, play some pillar music.

Oh yeah that would be a good way to deal with it

> Mobius can appear twice -> Pyramid was vanished from existence. Will come back though. Not ideal!

Would be good to fix, but need to figure out how to reproduce. Doesn't break anything, so low-priority.

> Third scroll might be too hidden, could bring it forward or have it stick out further

Going to put it in the middle of the ceiling, clearly in plain sight and reach.

> Make coordinates glow like ghost matter

Agreed. Should remove the need for using the flashlight to see it.

> Maybe in Nomai interface puzzle ship log we emphasize how it moves up and down? Emphasize that the gravity field is stuck on (maybe a broken interface to turn it off). Maybe only have the gravity field at the very top of the corner so it doesn't affect you getting onto the platform. Could also make the platform wider at the top so that standing on it feels purposeful.

Hopefully moving the scroll should make extending the platform less necessary. Going to reduce the gravity a bit to make it easier to get on the interface. Is there a broken tractor beam controller in the base game?

> Changing the totems to just be a toggle and not actually use the flashlight OR add a stranger artifact. Too easy to accidentally turn on the totems

I'd prefer to add a tutorial prompt like the "Y - Signalscope" prompts used in base game. "F- Turn on/off Flashlight" and we do that until they've lit and extinguished two totems. Not a fan of adding an artifact since people will probably think they're relevant for another puzzle.

> Could remove extinguish prompts from candles since its not relevant

As above. I'd prefer to make them work as vanilla.

> Add Ernesto

But where?

> Maybe add lights to the totems

Yeah.

> Lining up totems maybe too precise?

I could make the symbol a bit larger.

> Make the three coloured arrows stop being interactive after both puzzles are solved

Cool.

> Could get a more obvious hint that you want to go to the map mode, since they never open map mode they dont know about the double-hexagon until they read the hint

Yeah I'll change the wording a bit.

> Ixrec thought the upsidedown coords + leftshift meant to rightshift them rightside up, but figured out the right solution after that didnt work

Yeah I don't think that needs changing. Maybe adjust the line slightly.

> He wrote down all the map mode symbols, took a while to realize up meant go up. Could have the symbols be > > > > > ^ < <

Agreed.

> Mute ambient music when using signalscope in the hanger

Sure.

> Make nomai scrolls more obviously point in a direction. Maybe the text could have an arrow?

Nah, we don't want to rely too much on text. The ship log already points it out.
